version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MONGO_INITDB_DATABASE: ecommerce
    volumes:
      - mongo-data:/data/db
      - ../db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - ecommerce-overlay
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    secrets:
      - db_password
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis for Caching and Message Queue
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes --requirepass redispass123
    volumes:
      - redis-data:/data
    networks:
      - ecommerce-overlay
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      update_config:
        parallelism: 1
        delay: 10s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Backend API (Scalable)
  backend:
    image: ecommerce-backend:latest
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password123@mongo:27017/ecommerce?authSource=admin
      - REDIS_URL=redis://:redispass123@redis:6379
      - JWT_SECRET=8d5b9f7c3edsadfs3312fs3
      - JWT_REFRESH_SECRET=8d5b9f7c3edsadfs3312fs3
      - CLIENT_URL=http://localhost
      - GOOGLE_CLIENT_ID=9344810407-osvertrpda4c558fig5dtermllgoa4it.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
      - FACEBOOK_APP_ID=1429522254778730
      - FACEBOOK_APP_SECRET=0d2ddef64ebd86aedbf08338c997324f
      - EMAIL_HOST=smtp.gmail.com
      - EMAIL_PORT=587
      - EMAIL_USER=t10n12namjore@gmail.com
      - EMAIL_PASS=ahpx cpvb rjds xqvh
    volumes:
      - backend-uploads:/app/uploads
    networks:
      - ecommerce-overlay
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 60s
        max_failure_ratio: 0.3
      rollback_config:
        parallelism: 1
        delay: 10s
        failure_action: pause
        monitor: 60s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
        - "com.ecommerce.service=backend"
        - "com.ecommerce.version=1.0"
    secrets:
      - jwt_secret
      - email_user
      - email_password
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - mongo
      - redis

  # Email Queue Worker (Background Job Processor)
  worker:
    image: ecommerce-backend:latest
    command: ["node", "src/services/queue/worker.js"]
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password123@mongo:27017/ecommerce?authSource=admin
      - REDIS_URL=redis://:redispass123@redis:6379
      - EMAIL_HOST=${EMAIL_HOST:-smtp.gmail.com}
      - EMAIL_PORT=${EMAIL_PORT:-587}
      - EMAIL_USER_FILE=/run/secrets/email_user
      - EMAIL_PASS_FILE=/run/secrets/email_password
    networks:
      - ecommerce-overlay
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
      labels:
        - "com.ecommerce.service=worker"
    secrets:
      - email_user
      - email_password
    healthcheck:
      test: ["CMD", "node", "-e", "require('./src/services/queue/redisClient').pingRedis().then(r => process.exit(r ? 0 : 1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - mongo
      - redis

  # Frontend React App
  frontend:
    image: ecommerce-frontend:latest
    environment:
      - REACT_APP_API_URL=http://localhost
      - REACT_APP_SOCKET_URL=http://localhost
    networks:
      - ecommerce-overlay
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.25'
          memory: 256M
        reservations:
          cpus: '0.1'
          memory: 128M
      labels:
        - "com.ecommerce.service=frontend"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Load Balancer & Reverse Proxy
  nginx:
    image: nginx:alpine
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
      - target: 8080
        published: 8080
        protocol: tcp
        mode: ingress
    volumes:
      - backend-uploads:/app/uploads:ro
    networks:
      - ecommerce-overlay
    configs:
      - source: nginx_final_config
        target: /etc/nginx/conf.d/default.conf
        mode: 0444
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
      labels:
        - "com.ecommerce.service=nginx"
        - "com.ecommerce.type=loadbalancer"

  # Docker Swarm Visualizer (Optional - for demo)
  visualizer:
    image: dockersamples/visualizer:latest
    ports:
      - "9000:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - ecommerce-overlay
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.25'
          memory: 128M
        reservations:
          cpus: '0.1'
          memory: 64M
      labels:
        - "com.ecommerce.service=visualizer"

volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local
  backend-uploads:
    driver: local

networks:
  ecommerce-overlay:
    driver: overlay
    attachable: true
    ipam:
      config:
        - subnet: 10.0.9.0/24

secrets:
  db_password:
    external: true
  jwt_secret:
    external: true
  email_user:
    external: true
  email_password:
    external: true

configs:
  nginx_final_config:
    external: true
